server:
  port: 8080

spring:
  application:
    name: melitest
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver

melitest:
  client:
    address:
        url: http://localhost:8081
